# config.yaml example:
# reference: "path/to/reference.fasta"
# samples: ["sample1", "sample2", "sample3"]
# threads: 8

configfile: "config.yaml"

rule all:
    input:
        expand("results/bam/{sample}.sorted.bam.bai", sample=config["samples"])

rule bwa_index:
    input:
        ref = config["reference"]
    output:
        multiext(config["reference"], ".amb", ".ann", ".bwt", ".pac", ".sa")
    log:
        "logs/bwa_index.log"
    shell:
        "bwa index {input.ref} 2> {log}"

rule bwa_mem:
    input:
        ref = config["reference"],
        reads = "data/{sample}.fasta",
        idx = multiext(config["reference"], ".amb", ".ann", ".bwt", ".pac", ".sa")
    output:
        temp("results/sam/{sample}.sam")
    log:
        "logs/bwa_mem/{sample}.log"
    threads: config["threads"]
    shell:
        "bwa mem -t {threads} "
        "-R '@RG\\tID:{wildcards.sample}\\tSM:{wildcards.sample}' "
        "{input.ref} {input.reads} > {output} 2> {log}"

rule sam_to_bam:
    input:
        "results/sam/{sample}.sam"
    output:
        temp("results/bam/{sample}.bam")
    log:
        "logs/sam_to_bam/{sample}.log"
    shell:
        "samtools view -bS {input} > {output} 2> {log}"

rule sort_bam:
    input:
        "results/bam/{sample}.bam"
    output:
        "results/bam/{sample}.sorted.bam"
    log:
        "logs/sort_bam/{sample}.log"
    threads: config["threads"]
    shell:
        "samtools sort -@ {threads} {input} -o {output} 2> {log}"

rule index_bam:
    input:
        "results/bam/{sample}.sorted.bam"
    output:
        "results/bam/{sample}.sorted.bam.bai"
    log:
        "logs/index_bam/{sample}.log"
    shell:
        "samtools index {input} 2> {log}"
